FROM node:16-alpine
EXPOSE 5000
COPY . /usr/src/app
WORKDIR /usr/src/app
#ENV REACT_APP_BACKEND_URL=http://localhost:8080
RUN npm install && apk add --no-cache xsel && \
npm run build && npm install -g serve && adduser -D appuser
USER appuser
CMD ["serve", "-s", "-l", "5000", "build"]
