FROM node:16
EXPOSE 5000
COPY . /usr/src/app
WORKDIR /usr/src/app
#ENV REACT_APP_BACKEND_URL=http://localhost:8080
RUN npm install && apt-get update && apt-get install -y xsel && \
npm run build && npm install -g serve && useradd -m appuser && \
rm -rf /var/lib/apt/lists/*
USER appuser
CMD ["serve", "-s", "-l", "5000", "build"]
