FROM node:16-alpine AS build-stage
COPY . /usr/src/app
WORKDIR /usr/src/app
#ENV REACT_APP_BACKEND_URL=http://localhost:8080
RUN npm install && npm run build

FROM node:16-alpine
WORKDIR /usr/src/app
RUN apk add --no-cache xsel && npm install -g serve
COPY --from=build-stage /usr/src/app/build ./build
RUN adduser -D appuser
USER appuser
EXPOSE 5000
CMD ["serve", "-s", "-l", "5000", "build"]
