version: '3.8'

services:
  app:
    image: frontend
    build:
      context: ./example-frontend
      dockerfile: Dockerfile_ex2-9_frontend
    environment:
      REACT_APP_BACKEND_URL: http://localhost/api/
    #ports:
    #  - 5000:5000
    container_name: frontend

  server:
    image: backend
    build:
      context: ./example-backend
      dockerfile: Dockerfile_ex2-9_backend
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=tr
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=test_db
    #ports:
    #  - 8080:8080
    container_name: backend

  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: tr
      POSTGRES_DB: test_db
    volumes:
      - ./db_postgres:/var/lib/postgresql/data
    container_name: db

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: rev-proxy
    ports:
      - 80:80
    depends_on:
      - app
      - server
