version: '3.8'

services:
  simple-web-server:
    image: devopsdockeruh/simple-web-service
    build: .
    volumes:
      - ./logs/text.log:/usr/src/app/text.log
    command: devopsdockeruh/simple-web-service server
    ports:
      - 3000:8080
    container_name: simple-web-server
