FROM node:16
EXPOSE 5000
COPY . /usr/src/app
WORKDIR /usr/src/app
#ENV REACT_APP_BACKEND_URL=http://localhost:8080
RUN npm install
RUN apt-get update && apt-get install -y xsel
RUN npm run build
RUN npm install -g serve
CMD ["serve", "-s", "-l", "5000", "build"]
