FROM node:16-alpine AS build-stage
WORKDIR /usr/src/app
COPY . .
RUN adduser -D appuser
RUN npm install && npm run build

FROM node:16-alpine
WORKDIR /usr/src/app
RUN apk add --no-cache xsel && npm install -g serve
COPY --from=build-stage /etc/passwd /etc/passwd
COPY --from=build-stage /usr/src/app/build ./build

USER appuser
EXPOSE 3000
CMD ["serve", "-s", "-l", "3000", "build"]
